### ISSUE TITLE
multi objective function question

### ISSUE THREAD

**Issue by hfahad** [ruchtem/cosmos#1]
Hi all,
Nice work, I hafiz fahad working at German cancer research center (DKFZ.) Heidelberg Germany.
I have a question related to this method. 
1) Can you please tell me if we have several parameters (5 or 6) which defines the objective 1 and objective 2 in the end after training this model will also gives us these optimize parameters as well related to objective functions?
2) If we need to minimize the objective 1 and maximize the objective 2 so what shoud we do? (suggestion just use - sign with objective 2)?
3) What about if we have a 2 different fit models for 2 objective functions what should we need to?
best,
Hafiz

**Comment by ruchtem** [comment]
Hi Hafiz, sorry, I saw your question just now. I'll paste my replies from our email conversation here for others to follow too:

1) I'm not sure what kind of model you are referring to. Our method is designed for neural networks which come with many more than 5 or 6 parameters.
2) Yes, use the negative.
3) Then you don't need multi-objective, you can just optimize each model for each objective.

If you have any question left feel free to reopen the issue. Best, Michael

**Comment by hfahad** [comment]
Hi Thank you for reply, I have one more question if we have some constraints like equality and inequality constraint how we can deal with this in your model?
best,
Hafiz
